appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: a89pZKCqZir1yINN0ciVSNa0jJq65/UEkwXRNYjPl+DW6SFZ9KJ3A6edctHqvISMrC/DyJctTHAi9Zur9iqnwyOWNJe+l8CZ+P135L+ExSwmBI8+XSawYSQZgrk2pn8bXXGjkvBmiOKjZJJN8Bd+NUomT0S3Z/hfxMoaxbaPgGALFAPXcTatQ5YS5Eid+WEat1vF0sWgb5xlirwvq4Vijn1H18Rdu1ARE+7WPl4HoLakOCbw9GE/Cy2RojpiST2EQCyQRIgNKR1kvsWeQtO20/EBNNtW1bty8b3fTWeWUuUtBoanUQhHPHsKI+IoHIrHeb5VDgBgqiQmgx/8qQuA5tM4/sAk/4suaenv+Uh7bx8JGN7y3Gg3hxeQEaIsEzXwTmaNQbOvc/kyXCucmdBzyhbgCCWiEm5AqtQyK5dZ0uL89iqKlyNYiwLgx+auXpogunI9vPow5FurSvYUlqRa0TRmSGkiVZTFL+USOW3gwLwCSePeKWqLeNPuz0Wtel+OwSGes0c9l9LbqbXKt66Kq+3YoKYX+VqTO/ZiFQJIbKyt8g3ngknWH+iu66Cfo70QUqyLGPPuIsdsNO/IXeqihmHloaRCBxf6QR0JJRfi8TsUJZWZpdbzFVek5SOYjy36ihx6va+Fz038IIzLvKQWh2ugQJe1vmuqxnAERiWhxKU=
conda_forge_output_validation: false
